CREATE DATABASE vaccination;
USE vaccination;
CREATE TABLE adsite (
  AD_NAME varchar(50) NOT NULL,
  AD_STREET1 varchar(150) NOT NULL,
  AD_STREET2 varchar(150) DEFAULT NULL,
  AD_CITY varchar(50) NOT NULL,
  AD_STATE varchar(2) NOT NULL,
  AD_ZIPCODE varchar(11) NOT NULL,
  PRIMARY KEY (AD_NAME,AD_ZIPCODE)
);


INSERT INTO adsite VALUES ('CVS','9845 Clayton Rd','None','Saint Louis','MO','68345');

CREATE TABLE insurance (
  INSU_ID varchar(50) NOT NULL,
  PA_LNAME varchar(25) NOT NULL,
  PA_FNAME varchar(25) NOT NULL,
  PA_BIRTHDATE date NOT NULL,
  PA_ZIPCODE varchar(11) NOT NULL,
  INSU_HOLDER varchar(150) NOT NULL,
  INSU_INSURER varchar(150) NOT NULL,
  PRIMARY KEY (INSU_ID),
  KEY PA_LNAME (PA_LNAME,PA_FNAME,PA_BIRTHDATE,PA_ZIPCODE),
  CONSTRAINT insurance_ibfk_1 FOREIGN KEY (PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE) REFERENCES patient (PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE)
);


INSERT INTO insurance VALUES ('A12345678','Hendrix','Monica','2000-12-24','65123','Monica Hendrix','Ambetter');


CREATE TABLE patient (
  PA_LNAME varchar(25) NOT NULL,
  PA_INITIAL varchar(2) DEFAULT NULL,
  PA_FNAME varchar(25) NOT NULL,
  PA_BIRTHDATE date NOT NULL,
  PA_STREET1 varchar(150) NOT NULL,
  PA_STREET2 varchar(150) DEFAULT NULL,
  PA_CITY varchar(50) NOT NULL,
  PA_STATE varchar(2) NOT NULL,
  PA_ZIPCODE varchar(11) NOT NULL,
  PA_GENDER varchar(25) NOT NULL,
  PA_RACE varchar(100) NOT NULL,
  PA_ETHNIC varchar(150) NOT NULL,
  PRIMARY KEY (PA_LNAME,PA_FNAME,PA_BIRTHDATE,PA_ZIPCODE)
);



INSERT INTO patient VALUES ('Hendrix','K.','Monica','2000-12-24','1289 Grand Blvd','None','Saint Louis','MO','65123','Female','White','Not Hispanic or Latino');


CREATE TABLE provider (
  PRO_ID varchar(25) NOT NULL,
  PRO_LNAME varchar(25) NOT NULL,
  PRO_INITIAL varchar(2) DEFAULT NULL,
  PRO_FNAME varchar(25) NOT NULL,
  PRO_STREET1 varchar(150) NOT NULL,
  PRO_STREET2 varchar(150) DEFAULT NULL,
  PRO_CITY varchar(50) NOT NULL,
  PRO_STATE varchar(2) NOT NULL,
  PRO_ZIPCODE varchar(11) NOT NULL,
  PRIMARY KEY (PRO_ID)
);



INSERT INTO provider VALUES ('000001','Green','J.','Alissa','9845 Clayton Rd','None','Saint Louis','MO','68345');




CREATE TABLE vaccination (
  VACC_DOSENUM varchar(35) NOT NULL,
  VACC_TYPE varchar(50) DEFAULT NULL,
  VACC_CVX varchar(5) DEFAULT NULL,
  VACC_LOTNUM varchar(6) NOT NULL,
  VACC_MANU varchar(35) DEFAULT NULL,
  VACC_EXP date DEFAULT NULL,
  VACC_ADMINSITE varchar(25) DEFAULT NULL,
  VACC_DATEGIVEN date DEFAULT NULL,
  VACC_DOSEWASTE varchar(25) DEFAULT NULL,
  VACC_ADMINROUTE varchar(75) DEFAULT NULL,
  VACC_MISSEDAPPT varchar(10) NOT NULL,
  VACC_COMOR varchar(10) NOT NULL,
  VACC_REFUSAL varchar(10) NOT NULL,
  VACC_REFUSREASON varchar(50) DEFAULT NULL,
  VACC_VACCINATOR varchar(150) DEFAULT NULL,
  VACC_EUA varchar(10) NOT NULL,
  PRIMARY KEY (VACC_DOSENUM,VACC_LOTNUM)
);



INSERT INTO vaccination VALUES ('1st Dose','COVID-19','208','EW5612','Pfizer','2021-12-31','Left Arm','2021-11-15','0','C28161 (Intramuscular)','No','No','No','','Julia','Yes');



CREATE TABLE vacrecord (
  PA_LNAME varchar(25) NOT NULL,
  PA_FNAME varchar(25) NOT NULL,
  PA_BIRTHDATE date NOT NULL,
  PA_ZIPCODE varchar(11) NOT NULL,
  VACC_DOSENUM varchar(35) NOT NULL,
  VACC_LOTNUM varchar(6) NOT NULL,
  PRIMARY KEY (PA_LNAME,PA_FNAME,PA_BIRTHDATE,PA_ZIPCODE,VACC_DOSENUM,VACC_LOTNUM),
  KEY VACC_DOSENUM (VACC_DOSENUM,VACC_LOTNUM),
  CONSTRAINT vacrecord_ibfk_1 FOREIGN KEY (PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE) REFERENCES patient (PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE),
  CONSTRAINT vacrecord_ibfk_2 FOREIGN KEY (VACC_DOSENUM, VACC_LOTNUM) REFERENCES vaccination (VACC_DOSENUM, VACC_LOTNUM)
);



INSERT INTO vacrecord VALUES ('Hendrix','Monica','2000-12-24','65123','1st Dose','EW5612');



CREATE TABLE visit (
  VISIT_ID int(11) NOT NULL AUTO_INCREMENT,
  PA_LNAME varchar(25) NOT NULL,
  PA_FNAME varchar(25) NOT NULL,
  PA_BIRTHDATE date NOT NULL,
  PA_ZIPCODE varchar(11) NOT NULL,
  PRO_ID varchar(25) NOT NULL,
  AD_NAME varchar(50) NOT NULL,
  AD_ZIPCODE varchar(11) NOT NULL,
  PRIMARY KEY (VISIT_ID),
  KEY PA_LNAME (PA_LNAME,PA_FNAME,PA_BIRTHDATE,PA_ZIPCODE),
  KEY PRO_ID (PRO_ID),
  KEY AD_NAME (AD_NAME,AD_ZIPCODE),
  CONSTRAINT visit_ibfk_1 FOREIGN KEY (PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE) REFERENCES patient (PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE),
  CONSTRAINT visit_ibfk_2 FOREIGN KEY (PRO_ID) REFERENCES provider (PRO_ID),
  CONSTRAINT visit_ibfk_3 FOREIGN KEY (AD_NAME, AD_ZIPCODE) REFERENCES adsite (AD_NAME, AD_ZIPCODE)
);



INSERT INTO visit VALUES (1,'Hendrix','Monica','2000-12-24','65123','000001','CVS','68345');


