CREATE DATABASE vaccination;
use vaccination;

CREATE TABLE PATIENT (
PA_LNAME VARCHAR(25) NOT NULL,
PA_INITIAL VARCHAR(10) NULL,
PA_FNAME VARCHAR(25) NOT NULL,
PA_BIRTHDATE DATE NOT NULL,
PA_STREET1 VARCHAR(150) NOT NULL,
PA_STREET2 VARCHAR(150) NULL,
PA_CITY VARCHAR(50) NOT NULL,
PA_STATE VARCHAR(2) NOT NULL,
PA_ZIPCODE VARCHAR(11) NOT NULL,
PA_GENDER VARCHAR(25) NOT NULL,
PA_RACE VARCHAR(100) NOT NULL,
PA_ETHNIC VARCHAR(150) NOT NULL,
PRIMARY KEY (PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE));

CREATE TABLE INSURANCE (
INSU_ID INT AUTO_INCREMENT PRIMARY KEY,
INSU_GROUPID VARCHAR(50) NOT NULL,
PA_LNAME VARCHAR(25) NOT NULL,
PA_FNAME VARCHAR(25) NOT NULL,
PA_BIRTHDATE DATE NOT NULL,
PA_ZIPCODE VARCHAR(11) NOT NULL,
INSU_HOLDER VARCHAR(150) NOT NULL,
INSU_INSURER VARCHAR(150) NOT NULL,
FOREIGN KEY (PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE) REFERENCES PATIENT(PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE PROVIDER (
PRO_ID VARCHAR(25) NOT NULL,
PRO_LNAME VARCHAR(25) NOT NULL,
PRO_INITIAL VARCHAR(10) NULL,
PRO_FNAME VARCHAR(25) NOT NULL,
PRO_STREET1 VARCHAR(150) NOT NULL,
PRO_STREET2 VARCHAR(150) NULL,
PRO_CITY VARCHAR(50) NOT NULL,
PRO_STATE VARCHAR(2) NOT NULL,
PRO_ZIPCODE VARCHAR(11) NOT NULL,
PRIMARY KEY (PRO_ID));

CREATE TABLE ADSITE (
AD_NAME VARCHAR(50) NOT NULL,
AD_STREET1 VARCHAR(150) NOT NULL,
AD_STREET2 VARCHAR(150) NULL,
AD_CITY VARCHAR(50) NOT NULL,
AD_STATE VARCHAR(2) NOT NULL,
AD_ZIPCODE VARCHAR(11) NOT NULL,
PRIMARY KEY (AD_NAME, AD_ZIPCODE));

CREATE TABLE VISIT (
VISIT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
PA_LNAME VARCHAR(25) NOT NULL,
PA_FNAME VARCHAR(25) NOT NULL,
PA_BIRTHDATE DATE NOT NULL,
PA_ZIPCODE VARCHAR(11) NOT NULL,
PRO_ID VARCHAR(25) NOT NULL,
AD_NAME VARCHAR(50) NOT NULL,
AD_ZIPCODE VARCHAR(11) NOT NULL,
FOREIGN KEY (PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE) REFERENCES PATIENT(PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (PRO_ID) REFERENCES PROVIDER(PRO_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (AD_NAME, AD_ZIPCODE) REFERENCES ADSITE(AD_NAME, AD_ZIPCODE) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE VACCINATION (
VACC_DOSENUM VARCHAR(35) NOT NULL,
VACC_TYPE VARCHAR(50) NULL,
VACC_CVX VARCHAR(10) NULL,
VACC_LOTNUM VARCHAR(6) NOT NULL,
VACC_MANU VARCHAR(35) NULL,
VACC_EXP DATE NULL,
VACC_ADMINSITE VARCHAR(25) NULL,
VACC_DATEGIVEN DATE NULL,
VACC_DOSEWASTE VARCHAR(25) NULL,
VACC_ADMINROUTE VARCHAR(75) NULL,
VACC_MISSEDAPPT VARCHAR(10) NOT NULL,
VACC_COMOR VARCHAR(10) NOT NULL,
VACC_REFUSAL VARCHAR(10) NOT NULL,
VACC_REFUSREASON VARCHAR (50) NULL,
VACC_VACCINATOR VARCHAR(150) NULL,
VACC_EUA VARCHAR(10) NOT NULL,
PRIMARY KEY(VACC_DOSENUM,VACC_LOTNUM));

CREATE TABLE VACRECORD(
PA_LNAME VARCHAR(25) NOT NULL,
PA_FNAME VARCHAR(25) NOT NULL,
PA_BIRTHDATE DATE NOT NULL,
PA_ZIPCODE VARCHAR(11) NOT NULL,
VACC_DOSENUM VARCHAR(35) NOT NULL,
VACC_LOTNUM VARCHAR(6) NOT NULL,
PRIMARY KEY (PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE, VACC_DOSENUM, VACC_LOTNUM),
FOREIGN KEY (PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE) REFERENCES PATIENT(PA_LNAME, PA_FNAME, PA_BIRTHDATE, PA_ZIPCODE) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (VACC_DOSENUM, VACC_LOTNUM) REFERENCES VACCINATION(VACC_DOSENUM, VACC_LOTNUM) ON DELETE CASCADE ON UPDATE CASCADE);
